# ===================================================================
# Spring Boot configuration for the "prod" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# ===================================================================

logging:
    level:
        ROOT: INFO
        com.egov.elearning: INFO
        io.github.jhipster: INFO

spring:
    devtools:
        restart:
            enabled: false
        livereload:
            enabled: false
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:mysql://localhost:3306/egovcourses?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password: root
        hikari:
            auto-commit: false
            data-source-properties:
                cachePrepStmts: true
                prepStmtCacheSize: 250
                prepStmtCacheSqlLimit: 2048
                useServerPrepStmts: true
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        database: MYSQL
        show-sql: false
        properties:
            hibernate.id.new_generator_mappings: true
            hibernate.connection.provider_disables_autocommit: true
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
            hibernate.cache.region.factory_class: io.github.jhipster.config.jcache.BeanClassLoaderAwareJCacheRegionFactory
    data:
        jest:
            uri: http://localhost:9200
    liquibase:
        contexts: prod
    mail:
        host: aspmx.l.google.com # SMTP server host.
        port: 25 # SMTP server port.
        username: 
        password: 
        protocol: smtp
    thymeleaf:
        cache: true

server:
    port: 8080
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
        min-response-size: 1024

jhipster:
    http:
        version: V_1_1 
        cache: # Used by the CachingHttpHeadersFilter
            timeToLiveInDays: 1461
    cache: # Cache configuration
        ehcache: # Ehcache configuration
            time-to-live-seconds: 3600 # By default objects stay 1 hour in the cache
            max-entries: 1000 # Number of objects in each cache entry
    security:
        authentication:
            jwt:
                # This token must be encoded using Base64
                base64-secret: NGRlZjNlM2I5ZjNiOWJiMGRjNjVmZjJhZDQyMzY3NjRmNzgyOGUyN2U0NzM5MDg0NDAzOGU2Yzg4ZDEwY2EzOTk2MGNkODZkZTE2YzUzZjAxZmZiYWI1NDRhMTcyYmQ1ZjYwMTA2OTgxYjY5ZWNmOTlkZTdjYjFjZTQxMzFmYTI=
                # Token is valid 24 hours
                token-validity-in-seconds: 86400
                token-validity-in-seconds-for-remember-me: 2592000
    mail: 
        from: egovcourses@localhost
        base-url: http://my-server-url-to-change 
    metrics: 
        jmx:
            enabled: true
        prometheus: 
            enabled: false 
        logs: 
            enabled: false
            report-frequency: 60 # in seconds
    logging:
        logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
            enabled: false
            host: localhost
            port: 5000
            queue-size: 512